services:
  - type: web
    name: beautyshop-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: postgresql://beautyshop:lizH0DfeQ2yITNxqIsnfjqneLj0JW6el@dpg-d4mstge3jp1c73a6tlag-a.render.com:5432/beautyshop_k7uo
      - key: Jwt__Secret
        generateValue: true
      - key: Jwt__Issuer
        value: ECommerceAPI
      - key: Jwt__Audience
        value: ECommerceClient
